Добавил тесты для Sort и Limit. Добавил новые тесты для Model. Обнови…
leadvertex/plugin-component-db pull request #5
Opened 2020-02-11 16:03 UTC by LightFuri

…л контрольную базу.

2020-02-11 16:19 UTC, XAKEPEHOK requested changes

2020-02-11 16:19 UTC, XAKEPEHOK commented on tests/LimitTest.php
> +        $this->assertEquals(5, $limit->get());
а offset если он опущен?

2020-02-11 16:19 UTC, XAKEPEHOK commented on tests/ModelTest.php
> +        $model->newData = ['ololo' => ['alala']];
не проверяешь присвоение null

2020-02-11 16:19 UTC, XAKEPEHOK commented on tests/ModelTest.php
>          $this->assertEquals(3, $model->getFeature());
А теги? А data?

2020-02-11 16:19 UTC, XAKEPEHOK commented on tests/ModelTest.php
> +    public function testSetObjectModelData()
Тут все же логично либо одну проверку с object, либо если так хочется, то логичнее через dataProvider сделать

2020-02-11 16:19 UTC, XAKEPEHOK commented on tests/ModelTest.php
>          $this->assertEquals($uuid, $loadedModel->getId());
То же самое. Ты проверяешь сохранение. Вдруг из базы читается верно (что должен покрыть тест выше), а пишется нет?

2020-02-11 16:19 UTC, XAKEPEHOK commented on tests/ModelTest.php
> +        $model->setUpdatedAt($updateTime);
data?

2020-02-11 16:19 UTC, XAKEPEHOK commented on tests/ModelTest.php
>          $model->delete();
assertTrue?

2020-02-11 16:19 UTC, XAKEPEHOK commented on tests/SortTest.php
> +        $this->expectException(InvalidArgumentException::class);
Стоит добавить в Sort разные коды ошибок для InvalidArgumentException чтобы отличать исключения. Например просто код 1 и 2

2020-02-11 16:25 UTC, LightFuri commented on tests/LimitTest.php
> +        $this->assertEquals(5, $limit->get());
get() у Limit возвращает только $limit если $offset был опущен

2020-02-12 11:11 UTC, XAKEPEHOK approved these changes

2020-02-12 11:11 UTC, merged